### ISSUE TITLE
Today

### ISSUE THREAD

**Issue by snuss967** [GetHip-Zach/GetHIP#3]
What happened today? Where are we at? What needs to be done with our limited time left?
Can someone fill Taylor and I in?

**Comment by jhuang277** [comment]
The back end is pretty much wrapped up. Martin and Gabi are making real good progress on the UI. All we need is to put it all together and do a little more fine tuning, and we should be good.

**Comment by snuss967** [comment]
What if anything do you need done Martin and Gabi? Some of the javascript I put up before yesterday should help you don't have to use any of it, it just takes care of most of the dynamic stuff on the pages. 
Let me know where anyone needs help, I know that goes for Taylor. 
Thanks
